//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BF9UnloadBunkerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BF9UnloadBunkerResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.App_LocalResources.BF9UnloadBunkerResource", typeof(BF9UnloadBunkerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по массе.
        /// </summary>
        public static string control_mode_mass {
            get {
                return ResourceManager.GetString("control_mode_mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по времени.
        /// </summary>
        public static string control_mode_time {
            get {
                return ResourceManager.GetString("control_mode_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А.
        /// </summary>
        public static string mode_auto {
            get {
                return ResourceManager.GetString("mode_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматический режим.
        /// </summary>
        public static string mode_auto_full {
            get {
                return ResourceManager.GetString("mode_auto_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Д.
        /// </summary>
        public static string mode_remote {
            get {
                return ResourceManager.GetString("mode_remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дистанционный режим.
        /// </summary>
        public static string mode_remote_full {
            get {
                return ResourceManager.GetString("mode_remote_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол загрузки БЗУ ДП-9..
        /// </summary>
        public static string report_title {
            get {
                return ResourceManager.GetString("report_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бункер :.
        /// </summary>
        public static string report_ub_field_bunker {
            get {
                return ResourceManager.GetString("report_ub_field_bunker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время :.
        /// </summary>
        public static string report_ub_field_dateandtime {
            get {
                return ResourceManager.GetString("report_ub_field_dateandtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Факт\Загр.
        /// </summary>
        public static string report_ub_field_factzagr {
            get {
                return ResourceManager.GetString("report_ub_field_factzagr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лоток :.
        /// </summary>
        public static string report_ub_field_lotok {
            get {
                return ResourceManager.GetString("report_ub_field_lotok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материал:.
        /// </summary>
        public static string report_ub_field_material {
            get {
                return ResourceManager.GetString("report_ub_field_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим  :.
        /// </summary>
        public static string report_ub_field_mode {
            get {
                return ResourceManager.GetString("report_ub_field_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим управления :.
        /// </summary>
        public static string report_ub_field_modeupr {
            get {
                return ResourceManager.GetString("report_ub_field_modeupr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер порции :.
        /// </summary>
        public static string report_ub_field_num_porc {
            get {
                return ResourceManager.GetString("report_ub_field_num_porc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отклонение :.
        /// </summary>
        public static string report_ub_field_otklonenie {
            get {
                return ResourceManager.GetString("report_ub_field_otklonenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П1.
        /// </summary>
        public static string report_ub_field_p1 {
            get {
                return ResourceManager.GetString("report_ub_field_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П1-2.
        /// </summary>
        public static string report_ub_field_p1_2 {
            get {
                return ResourceManager.GetString("report_ub_field_p1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П10.
        /// </summary>
        public static string report_ub_field_p10 {
            get {
                return ResourceManager.GetString("report_ub_field_p10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П10-11.
        /// </summary>
        public static string report_ub_field_p10_11 {
            get {
                return ResourceManager.GetString("report_ub_field_p10_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П11.
        /// </summary>
        public static string report_ub_field_p11 {
            get {
                return ResourceManager.GetString("report_ub_field_p11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П11-.
        /// </summary>
        public static string report_ub_field_p11_ {
            get {
                return ResourceManager.GetString("report_ub_field_p11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П2.
        /// </summary>
        public static string report_ub_field_p2 {
            get {
                return ResourceManager.GetString("report_ub_field_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П2-3.
        /// </summary>
        public static string report_ub_field_p2_3 {
            get {
                return ResourceManager.GetString("report_ub_field_p2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П3.
        /// </summary>
        public static string report_ub_field_p3 {
            get {
                return ResourceManager.GetString("report_ub_field_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П3-4.
        /// </summary>
        public static string report_ub_field_p3_4 {
            get {
                return ResourceManager.GetString("report_ub_field_p3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П4.
        /// </summary>
        public static string report_ub_field_p4 {
            get {
                return ResourceManager.GetString("report_ub_field_p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П4-5.
        /// </summary>
        public static string report_ub_field_p4_5 {
            get {
                return ResourceManager.GetString("report_ub_field_p4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П5.
        /// </summary>
        public static string report_ub_field_p5 {
            get {
                return ResourceManager.GetString("report_ub_field_p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П5-6.
        /// </summary>
        public static string report_ub_field_p5_6 {
            get {
                return ResourceManager.GetString("report_ub_field_p5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П6.
        /// </summary>
        public static string report_ub_field_p6 {
            get {
                return ResourceManager.GetString("report_ub_field_p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П6-7.
        /// </summary>
        public static string report_ub_field_p6_7 {
            get {
                return ResourceManager.GetString("report_ub_field_p6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П7.
        /// </summary>
        public static string report_ub_field_p7 {
            get {
                return ResourceManager.GetString("report_ub_field_p7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П7-8.
        /// </summary>
        public static string report_ub_field_p7_8 {
            get {
                return ResourceManager.GetString("report_ub_field_p7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П8.
        /// </summary>
        public static string report_ub_field_p8 {
            get {
                return ResourceManager.GetString("report_ub_field_p8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П8-9.
        /// </summary>
        public static string report_ub_field_p8_9 {
            get {
                return ResourceManager.GetString("report_ub_field_p8_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П9.
        /// </summary>
        public static string report_ub_field_p9 {
            get {
                return ResourceManager.GetString("report_ub_field_p9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П9-10.
        /// </summary>
        public static string report_ub_field_p9_10 {
            get {
                return ResourceManager.GetString("report_ub_field_p9_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчетное.
        /// </summary>
        public static string report_ub_field_raschet {
            get {
                return ResourceManager.GetString("report_ub_field_raschet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С1.
        /// </summary>
        public static string report_ub_field_s1 {
            get {
                return ResourceManager.GetString("report_ub_field_s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С2.
        /// </summary>
        public static string report_ub_field_s2 {
            get {
                return ResourceManager.GetString("report_ub_field_s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С3.
        /// </summary>
        public static string report_ub_field_s3 {
            get {
                return ResourceManager.GetString("report_ub_field_s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С4.
        /// </summary>
        public static string report_ub_field_s4 {
            get {
                return ResourceManager.GetString("report_ub_field_s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С5.
        /// </summary>
        public static string report_ub_field_s5 {
            get {
                return ResourceManager.GetString("report_ub_field_s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С6.
        /// </summary>
        public static string report_ub_field_s6 {
            get {
                return ResourceManager.GetString("report_ub_field_s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время выгрузки:.
        /// </summary>
        public static string report_ub_field_timeunload {
            get {
                return ResourceManager.GetString("report_ub_field_timeunload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угол открытия:.
        /// </summary>
        public static string report_ub_field_ugolotkr {
            get {
                return ResourceManager.GetString("report_ub_field_ugolotkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выгружено :.
        /// </summary>
        public static string report_ub_field_unload {
            get {
                return ResourceManager.GetString("report_ub_field_unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задание :.
        /// </summary>
        public static string report_ub_field_zadanie {
            get {
                return ResourceManager.GetString("report_ub_field_zadanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зонды.
        /// </summary>
        public static string report_ub_field_zonds {
            get {
                return ResourceManager.GetString("report_ub_field_zonds", resourceCulture);
            }
        }
    }
}
