//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.App_LocalResources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующая дата.
        /// </summary>
        public static string button_title_next {
            get {
                return ResourceManager.GetString("button_title_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущая дата.
        /// </summary>
        public static string button_title_previous {
            get {
                return ResourceManager.GetString("button_title_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать.
        /// </summary>
        public static string button_title_view {
            get {
                return ResourceManager.GetString("button_title_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О нас.
        /// </summary>
        public static string index_link_go_about_title {
            get {
                return ResourceManager.GetString("index_link_go_about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ к сайту.
        /// </summary>
        public static string index_link_go_access_title {
            get {
                return ResourceManager.GetString("index_link_go_access_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администрирование.
        /// </summary>
        public static string index_link_go_admin_title {
            get {
                return ResourceManager.GetString("index_link_go_admin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь и описание.
        /// </summary>
        public static string index_link_go_help_title {
            get {
                return ResourceManager.GetString("index_link_go_help_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АДД.
        /// </summary>
        public static string index_menu_name_add {
            get {
                return ResourceManager.GetString("index_menu_name_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аглодоменный департамент.
        /// </summary>
        public static string index_menu_name_add_full {
            get {
                return ResourceManager.GetString("index_menu_name_add_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CTO.
        /// </summary>
        public static string index_menu_name_cto {
            get {
                return ResourceManager.GetString("index_menu_name_cto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделения - CTO.
        /// </summary>
        public static string index_menu_name_cto_full {
            get {
                return ResourceManager.GetString("index_menu_name_cto_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЭД.
        /// </summary>
        public static string index_menu_name_ed {
            get {
                return ResourceManager.GetString("index_menu_name_ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энергетический департамент.
        /// </summary>
        public static string index_menu_name_ed_full {
            get {
                return ResourceManager.GetString("index_menu_name_ed_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПД.
        /// </summary>
        public static string index_menu_name_rd {
            get {
                return ResourceManager.GetString("index_menu_name_rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прокатный департамент.
        /// </summary>
        public static string index_menu_name_rd_full {
            get {
                return ResourceManager.GetString("index_menu_name_rd_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СД.
        /// </summary>
        public static string index_menu_name_sd {
            get {
                return ResourceManager.GetString("index_menu_name_sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сталеплавильный департамент.
        /// </summary>
        public static string index_menu_name_sd_full {
            get {
                return ResourceManager.GetString("index_menu_name_sd_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная информация:.
        /// </summary>
        public static string index_mmenu_title {
            get {
                return ResourceManager.GetString("index_mmenu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на технологических отчетов АМКР.
        /// </summary>
        public static string index_name_tehrep {
            get {
                return ResourceManager.GetString("index_name_tehrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web-сайт.
        /// </summary>
        public static string index_name_webside {
            get {
                return ResourceManager.GetString("index_name_webside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        public static string index_select_lang_en {
            get {
                return ResourceManager.GetString("index_select_lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string index_select_lang_ru {
            get {
                return ResourceManager.GetString("index_select_lang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык : .
        /// </summary>
        public static string index_select_lang_title {
            get {
                return ResourceManager.GetString("index_select_lang_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Украинский.
        /// </summary>
        public static string index_select_lang_uk {
            get {
                return ResourceManager.GetString("index_select_lang_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню.
        /// </summary>
        public static string layout_report_menu {
            get {
                return ResourceManager.GetString("layout_report_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущее меню.
        /// </summary>
        public static string layout_report_menu_previous {
            get {
                return ResourceManager.GetString("layout_report_menu_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возврат на главное меню.
        /// </summary>
        public static string layout_report_menu_title {
            get {
                return ResourceManager.GetString("layout_report_menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы обрабатываем ваш запрос....
        /// </summary>
        public static string lock_text {
            get {
                return ResourceManager.GetString("lock_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДЦ-1.
        /// </summary>
        public static string menu_report_add_bfs1 {
            get {
                return ResourceManager.GetString("menu_report_add_bfs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доменный цех -1.
        /// </summary>
        public static string menu_report_add_bfs1_full {
            get {
                return ResourceManager.GetString("menu_report_add_bfs1_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДЦ-2.
        /// </summary>
        public static string menu_report_add_bfs2 {
            get {
                return ResourceManager.GetString("menu_report_add_bfs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доменный цех -2.
        /// </summary>
        public static string menu_report_add_bfs2_full {
            get {
                return ResourceManager.GetString("menu_report_add_bfs2_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АЦ-1.
        /// </summary>
        public static string menu_report_add_sp1 {
            get {
                return ResourceManager.GetString("menu_report_add_sp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агломерационный цех -1.
        /// </summary>
        public static string menu_report_add_sp1_full {
            get {
                return ResourceManager.GetString("menu_report_add_sp1_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АЦ-2.
        /// </summary>
        public static string menu_report_add_sp2 {
            get {
                return ResourceManager.GetString("menu_report_add_sp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агломерационный цех -2.
        /// </summary>
        public static string menu_report_add_sp2_full {
            get {
                return ResourceManager.GetString("menu_report_add_sp2_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АЦ-3.
        /// </summary>
        public static string menu_report_add_sp3 {
            get {
                return ResourceManager.GetString("menu_report_add_sp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агломерационный цех -3.
        /// </summary>
        public static string menu_report_add_sp3_full {
            get {
                return ResourceManager.GetString("menu_report_add_sp3_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Левченко Эдуард.
        /// </summary>
        public static string name_developers_admin {
            get {
                return ResourceManager.GetString("name_developers_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Служба по СРиВ АСУТП.
        /// </summary>
        public static string name_developers_section {
            get {
                return ResourceManager.GetString("name_developers_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Служба по стратегическому развитию и внедрению АСУТП.
        /// </summary>
        public static string name_developers_section_full {
            get {
                return ResourceManager.GetString("name_developers_section_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка БЗУ ДП-9.
        /// </summary>
        public static string report_bf9_unload_bzu {
            get {
                return ResourceManager.GetString("report_bf9_unload_bzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дозирования материалов, ШП ДП-9.
        /// </summary>
        public static string report_bf9_unload_dosing {
            get {
                return ResourceManager.GetString("report_bf9_unload_dosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выгрузка материалов, ШП ДП-9.
        /// </summary>
        public static string report_bf9_unload_um {
            get {
                return ResourceManager.GetString("report_bf9_unload_um", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энергоресуры.
        /// </summary>
        public static string report_group_energy {
            get {
                return ResourceManager.GetString("report_group_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПУТ.
        /// </summary>
        public static string report_group_psi {
            get {
                return ResourceManager.GetString("report_group_psi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технология.
        /// </summary>
        public static string report_group_tehno {
            get {
                return ResourceManager.GetString("report_group_tehno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка.
        /// </summary>
        public static string report_group_unload {
            get {
                return ResourceManager.GetString("report_group_unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите период.
        /// </summary>
        public static string select_date_range_title {
            get {
                return ResourceManager.GetString("select_date_range_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите дату.
        /// </summary>
        public static string select_date_title {
            get {
                return ResourceManager.GetString("select_date_title", resourceCulture);
            }
        }
    }
}
