//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportEnergyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportEnergyResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.App_LocalResources.ReportEnergyResource", typeof(ReportEnergyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднесуточные значения.
        /// </summary>
        public static string form_ed_caption {
            get {
                return ResourceManager.GetString("form_ed_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднесуточные расходы.
        /// </summary>
        public static string form_efd_caption {
            get {
                return ResourceManager.GetString("form_efd_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднесуточные значения.
        /// </summary>
        public static string form_efd_field_avgvalue {
            get {
                return ResourceManager.GetString("form_efd_field_avgvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общий.
        /// </summary>
        public static string form_efd_field_common {
            get {
                return ResourceManager.GetString("form_efd_field_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расход за сутки.
        /// </summary>
        public static string form_efd_field_flowday {
            get {
                return ResourceManager.GetString("form_efd_field_flowday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛГУ.
        /// </summary>
        public static string form_efd_field_leftgranul {
            get {
                return ResourceManager.GetString("form_efd_field_leftgranul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс.
        /// </summary>
        public static string form_efd_field_max {
            get {
                return ResourceManager.GetString("form_efd_field_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string form_efd_field_name {
            get {
                return ResourceManager.GetString("form_efd_field_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Норма.
        /// </summary>
        public static string form_efd_field_norm {
            get {
                return ResourceManager.GetString("form_efd_field_norm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агрегат.
        /// </summary>
        public static string form_efd_field_object {
            get {
                return ResourceManager.GetString("form_efd_field_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планим. число.
        /// </summary>
        public static string form_efd_field_planometric {
            get {
                return ResourceManager.GetString("form_efd_field_planometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Давление.
        /// </summary>
        public static string form_efd_field_preassure {
            get {
                return ResourceManager.GetString("form_efd_field_preassure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расход приведен..
        /// </summary>
        public static string form_efd_field_prflow {
            get {
                return ResourceManager.GetString("form_efd_field_prflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПГУ.
        /// </summary>
        public static string form_efd_field_rightgranul {
            get {
                return ResourceManager.GetString("form_efd_field_rightgranul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Температура.
        /// </summary>
        public static string form_efd_field_temp {
            get {
                return ResourceManager.GetString("form_efd_field_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время подачи.
        /// </summary>
        public static string form_efd_field_time_norm {
            get {
                return ResourceManager.GetString("form_efd_field_time_norm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ед.изм..
        /// </summary>
        public static string form_efd_field_unit {
            get {
                return ResourceManager.GetString("form_efd_field_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        public static string form_efd_field_value {
            get {
                return ResourceManager.GetString("form_efd_field_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Придоменная грануляция шлака.
        /// </summary>
        public static string form_egd_caption {
            get {
                return ResourceManager.GetString("form_egd_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на энергоресурсы АДД.
        /// </summary>
        public static string report_add_section {
            get {
                return ResourceManager.GetString("report_add_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет потребления энергоресурсов АДД.
        /// </summary>
        public static string report_add_title {
            get {
                return ResourceManager.GetString("report_add_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на энергоресурсы ДЦ-1.
        /// </summary>
        public static string report_bfs1_section {
            get {
                return ResourceManager.GetString("report_bfs1_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет потребления энергоресурсов ДЦ-1.
        /// </summary>
        public static string report_bfs1_title {
            get {
                return ResourceManager.GetString("report_bfs1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на энергоресурсы ДЦ-2.
        /// </summary>
        public static string report_bfs2_section {
            get {
                return ResourceManager.GetString("report_bfs2_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет потребления энергоресурсов ДЦ-2.
        /// </summary>
        public static string report_bfs2_title {
            get {
                return ResourceManager.GetString("report_bfs2_title", resourceCulture);
            }
        }
    }
}
